#!/bin/bash
# Fix script generated by audit-movie-flow.js
# Failures: 3
# Run after fixing each issue, redeploy, and re-run: node audit-movie-flow.js

echo "Fix these 3 issues:"

# 1. Streaming API/resolver requests made: all 2 requests failed: https://vsembed.ru/embed/movie/27205/ (HTTP 200) | https://vidsrc.cc/embed/movie/27205 (ERR: net::ERR_ABORTED)
# 2. Clicking suggested card navigates to new movie: still on same page: https://streamium-cosmic.vercel.app/movie/tt1375666
# 3. TMDB API calls on detail page succeed: 2 failed TMDB calls: https://image.tmdb.org/t/p/w1280, https://anyembed.xyz/embed/tmdb-movie-27205

echo ""
echo "After fixing:"
echo "  1. git add . && git commit -m 'fix: movie flow issues' && git push"
echo "  2. Wait for Vercel deploy"
echo "  3. node audit-movie-flow.js   # re-run to verify"
echo "  4. Repeat until 0 failures"
